/* File Name: account.js
   Coded By: Tim & Jody
   Description: This JS file handles all of the functions on the account page.
    get: Takes in the date, time, and museum, and return a table with the corresponding info if the booking exists. Alerts the user if no such booking exists.
    remove: Takes in the same parameters and removes the booking if its exists; if not, it alerts the user that the booking does not exist.
    getDataSet: Iterates through the Firebase FRD and counts the number of child nodes each month has. Displays the counts in a bar chart generated by ChartJS.
    calendar: Displays a calendar view of the user's bookings using the FullCalendar JS library. Iterates through the data and pulls out the year, month, day, time, and museum for each booking.

*/





// ----------------- Firebase Setup & Initialization ------------------------//
// Import the functions you need from the SDKs you need
  import { initializeApp } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-app.js";
  import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword } 
    from "https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js";

  import {getDatabase, ref, set, update, child, get, onValue, remove}
    from "https://www.gstatic.com/firebasejs/12.6.0/firebase-database.js";

  import { onAuthStateChanged } from
    "https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js";


  // Your web app's Firebase configuration
  const firebaseConfig = {
    apiKey: "AIzaSyD2xfIz6jMWHXnRpMW5afLkNYPZllbBDdc",
    authDomain: "wd-2-fc227.firebaseapp.com",
    databaseURL: "https://wd-2-fc227-default-rtdb.firebaseio.com",
    projectId: "wd-2-fc227",
    storageBucket: "wd-2-fc227.firebasestorage.app",
    messagingSenderId: "31083722430",
    appId: "1:31083722430:web:87e89224c22a69793450ef"
    };


  // Initialize Firebase
  const app = initializeApp(firebaseConfig);

  // Initialize Firebase Authentication
  const auth = getAuth();

  // Return instance of your app's firebase realtime database (FRD)
  const db = getDatabase(app);


// This function retrieves the first name and userID of the current user to set the Welcome text.
function getUsername() {
  // Grab value for the 'keep logged in switch'
  let keepLoggedIn = localStorage.getItem("keepLoggedIn");

  // Grab user information passed from signIn.js
  if (keepLoggedIn == 'yes') {
    currentUser = JSON.parse(localStorage.getItem('user'));
  } else {
    currentUser = JSON.parse(sessionStorage.getItem('user'));
  }
}

// This function signs out the user after they click the button on the nav bar.
function SignOutUser() {
  sessionStorage.removeItem('user');  // Clear session storage
  localStorage.removeItem('user');     // Clear local storage
  localStorage.removeItem('keepLoggedIn');

  signOut(auth).then(() => {
    // Sign out successful
  }).catch((error) => {
    // Error occurred
  });

  window.location = "index.html";
}

// This function gets the data and displays it in a table.
function getData(userID, year, month, day, time, museum) {

  const dbref = ref(db); // Firebase parameter for getting data

  // Get references to the table elements
  const dateVal = document.getElementById('dateVal');
  const timeVal = document.getElementById('timeVal');
  const partySizeVal = document.getElementById('partySizeVal');
  const museumVal = document.getElementById('museumVal');
  const bookingTable = document.getElementById('bookingTable');

  // Provide the path through the nodes to the data
  get(child(dbref, 'users/' + userID + '/data/' + year + '/' + month + '/' + day + '/' + museum))
    .then((snapshot) => {
      if (snapshot.exists) {
        // If the snapshot exists, update the table text to display all of the info
        dateVal.textContent = month + '/' + day + '/' + year;
        timeVal.textContent = time;
        museumVal.textContent = museum;
        partySizeVal.textContent = snapshot.val()[time];

        // Display the table to the user
        bookingTable.classList.remove('visually-hidden');


      } else {
        alert("No booking found");
        bookingTable.classList.add('visually-hidden');
      }
  }).catch((error) => {
    // If the snapshot is not found, notify the user and hide the table.
    alert('No booking found!');
    bookingTable.classList.add('visually-hidden');
  });
}

// This function deletes the data at the specified path.
function deleteData(userID, year, month, day, time, museum) {
  
  // Before the node is removed, check if the booking actually exists.
  const dataRef = child(ref(db), 'users/' + userID + '/data/' + year + '/' + month + '/' + day + '/' + museum + '/' + time);
  get(dataRef)
    .then((snapshot) => {
      if (snapshot.exists()) {
        // If the node exists, remove it
        remove(dataRef)
          .then(() => {
            // Alert the user that the booking was removed and reload the page to reset the chart and calendar
            alert('Booking removed successfully!');
            location.reload();
          })
          .catch((error) => {
            console.error(error);
            alert('Error removing booking.');
          });
      } else {
        // If the node doesn't exist, alert the user
        alert('No such booking exists.');
      }
    })
    .catch((error) => {
      console.error(error);
      alert('Error checking booking.');
    });
}



// This async function iterates through the firebase FRD to get the number of bookings for each month to display in the chart.
async function getMonthCounts(year, uid) {
  // Get a reference to the user's data for the specified year (makes it easier to query because the chart is only displaying data for one year)
  const yearRef = ref(db, `users/${uid}/data/${year}`);
  const snapshot = await get(yearRef);

  const monthCounts = {};

  // Utilize the helper function to set the month names as keys
  for (let m = 1; m <= 12; m++) {
    monthCounts[monthNumberToName(m)] = 0;
  }

  if (snapshot.exists()) {
    // If the snapshot exists, iterate through the months and count the number of days per month
    snapshot.forEach((monthSnap) => {
      const month = monthNumberToName(parseInt(monthSnap.key));

      // Check if nodes under the month exist
      const value = monthSnap.val();

      // If yes, get the number of days in the month (the number of values); If not, set the count to zero
      const dayCount = value ? Object.keys(value).length : 0;

      // Add the dayCount to monthCounts
      monthCounts[month] = dayCount;
    });
  }
  return monthCounts;
}

// Helper function to getMonthCounts that converts the month number to its name for the bar chart labels.
function monthNumberToName(monthNumber) {
  return new Date(2000, monthNumber - 1).toLocaleString("en-US", {
    month: "long"
  });
}

// This async function creates the chart for the bookings.
async function createChart(year, uid) {
    // Utilize the getMonthCounts function to get the data for the chart
    const data = await getMonthCounts(year, uid);
    // Get the HTML object for the chart
    const barChart = document.getElementById('bookingMonths');
    // Create the chart using the keys as the x-axis and the values as the y-axis
    const myChart = new Chart(barChart, {
        type: 'bar',
        data: {
            labels: Object.keys(data),
            datasets: [{
                label: 'Number of Bookings',
                data: Object.values(data),
                borderWidth: 1,
                backgroundColor: '#ff5757',
                borderColor: '#FFC0CB',
            }]
        },
        options: {
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Month'
                    }
                },
                y: {
                    beginAtZero: true,
                    title: {
                        display: true,
                        text: 'Number of Bookings'
                    },
                    ticks: {
                      stepSize: 1
                    }
                }
            },
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    align: 'center',
                    position: 'bottom',
                },
                title: {
                    display: true,
                    text: `Your Bookings in ${year}`,
                    font: {
                        size: 32,
                        fontFamily: 'Playfair Display',
                        color: '#ff5757',
                    }
                }
            }
        },
    });

}

// This function listens to when the user adds new events and changes the calendar accordingly. 
function listenToEvents(user, year, callback) {

  // Get the database reference down to the year
  const yearRef = ref(db, `users/${user.uid}/data/${year}`);

  // Iterate through the nodes and pull out all the values
  onValue(yearRef, (snapshot) => {
    const events = [];

    if (snapshot.exists()) {
      // Go from year to month
      snapshot.forEach(monthSnap => {
        const month = monthSnap.key; 
        // Month to day
        monthSnap.forEach(daySnap => {
          const day = daySnap.key; 
          // Day to museum (location)
          daySnap.forEach(locationSnap => {
            // Location to time
            locationSnap.forEach(timeSnap => {
              const time = timeSnap.key; 

              // Year-Month-DayTHour:Minute (turn all the values into calendar format)
              const startDate = `${year}-${month}-${day}T${time}`;
              
              const details = timeSnap.val() || {};
              
              // Push all the details to the events dictionary
              events.push({
                id: `${year}-${month}-${day}-${locationSnap.key}-${time}`, 
                title: locationSnap.key,
                start: startDate,
                allDay: false,
                className: "calendarEvent",
                extendedProps: details
              });
            });
          });
        });
      });
    }

    // Runs the callback function, which removes all the events and reloads the calendar with the updated list
    callback(events);
  });
}



// Get the userLink element on the nav bar (on the account page it will display the signOut text)
let userLink = document.getElementById('userLink');   
let userLinkText = document.getElementById('userLinkText');
let currentUser = null;

// --------------------------- Home Page Loading -----------------------------
window.onload = function() {

  // Get current user's first name
  getUsername();
  
  // Update navbar with the signOut
  userLinkText.innerText = "Sign Out";
  userLink.href = "index.html";
  // When the userLink is clicked, signOut the user
  this.document.getElementById('userLink').onclick = function() {
      SignOutUser();
  };

  // Set Welcome Message
  document.getElementById("accountHeading").innerText = "Welcome, " + currentUser.firstName;

   // Get a datum function call

  document.getElementById('get').onclick = function(e){

    // Prevents page from reloading after the button is pressed
    e.preventDefault(); 

    // Pull all of the values
    const date = document.getElementById('bookingDate').value;
    const time = document.getElementById('bookingTime').value;
    const museum = document.getElementById('bookingMuseum').value;
    const userID = currentUser.uid;

    // Run the getData function with the user's ID and the selected date (broken up using substring()), time, and museum
    getData(userID, date.substring(0, 4), date.substring(5, 7), date.substring(8, 10), time, museum)
  }



  // Delete a single day's data function call
  document.getElementById('delete').onclick = function(e){

    // Prevents page from reloading after the button is pressed
    e.preventDefault();

    // Pull all of the values
    const date = document.getElementById('removeDate').value;
    const time = document.getElementById('removeTime').value;
    const museum = document.getElementById('removeMuseum').value;
    const userID = currentUser.uid;

    // Run deleteData with all of the inputted values
    deleteData(userID, date.substring(0, 4), date.substring(5, 7), date.substring(8, 10), time, museum);
  };

  // Get user id for the chart
  const userID = currentUser.uid;

  // Run the createChart function for the year 2026
  createChart("2026", userID);


  // Set up the calendar
  const calendarEl = document.getElementById("calendar");
  let calendar;

  // When the authState is changed, update the calendar
  onAuthStateChanged(auth, (user) => {

    // Double check if user is signed in
    if (!user) return;

    // Get the year values to determine where the calendar starts
    const year = new Date().getFullYear();

    // Make the calendar object with an empty events array
    calendar = new FullCalendar.Calendar(calendarEl, {
      initialView: "dayGridMonth",
      dayMaxEventRows: true,
      events: []
    });

    // Render the calendar
    calendar.render();

    // Populate the events array using listenToEvents
    listenToEvents(user, year, (events) => {
      calendar.removeAllEvents();
      calendar.addEventSource(events);
    });
  });

}
